github_owner             = "jwill824"
azure_resource_group     = "email-notion-sync-rg"
github_repo              = "email-notion-sync"
function_app_name        = "email-notion-sync-func"
azure_gmailapi_app_name  = "gmail-api"
azure_notionapi_app_name = "notion-api"