name: "build-and-test"
on:
  push:
    branches-ignore:
      - main
    # Run on all branches except main
    # If you want to also run on PRs, add pull_request trigger
  pull_request:
  workflow_dispatch:
    
permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore EmailNotionSync/EmailNotionSync.sln

      - name: Build
        run: dotnet build EmailNotionSync/EmailNotionSync.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test EmailNotionSync/EmailNotionSync.sln --no-build --configuration Release --logger trx