name: Build and Push API Images to GHCR

on:
  push:
    branches:
      - main
    paths:
      - 'EmailNotionSync/EmailNotionSync.GmailApi/**'
      - 'EmailNotionSync/EmailNotionSync.NotionApi/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        api:
          - name: gmailapi
            path: EmailNotionSync/EmailNotionSync.GmailApi
          - name: notionapi
            path: EmailNotionSync/EmailNotionSync.NotionApi
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.api.name }} image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ matrix.api.name }}:latest
          docker build -t $IMAGE_NAME ./${{ matrix.api.path }}
          docker push $IMAGE_NAME