on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-notion-api.yml'
      - 'EmailNotionSync/EmailNotionSync.NotionApi/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build and Push NotionApi Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push NotionApi image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/notionapi:latest
          docker build -t $IMAGE_NAME \
            --file ./EmailNotionSync/EmailNotionSync.NotionApi/Dockerfile \
            .
          docker push $IMAGE_NAME

  deploy:
    name: Deploy NotionApi Container App
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Update NotionApi Container App
        run: |
          az containerapp update \
            --name ${{ secrets.AZURE_NOTIONAPI_APP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --image ghcr.io/${{ github.repository_owner }}/notionapi:latest
